# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phillip Tran
email: ptrandev@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio Site of Phillip Tran: High School Student and Full Stack Developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ptran.dev" # the base hostname & protocol for your site
github_username: ptrandev
instagram_username: ptrandev

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    output: true

# Pagination
paginate: 12
paginate_path: "blog/page/:num/"
